name: CI - Backend

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build and test (backend folder)
        working-directory: ./backend
        run: mvn -B clean verify
